/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVerifyRouteImport } from './routes/_authenticated/verify'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiPublicRunCiScansRouteImport } from './routes/api/public/run-ci-scans'
import { Route as ApiPublicRefreshCrimeBenchmarksRouteImport } from './routes/api/public/refresh-crime-benchmarks'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app.reports'
import { Route as AuthenticatedAppOpportunityFinderRouteImport } from './routes/_authenticated/app.opportunity-finder'
import { Route as AuthenticatedAppMarketplaceRouteImport } from './routes/_authenticated/app.marketplace'
import { Route as AuthenticatedAppLocationAnalysisRouteImport } from './routes/_authenticated/app.location-analysis'
import { Route as AuthenticatedAppLearningRouteImport } from './routes/_authenticated/app.learning'
import { Route as AuthenticatedAppJourneyRouteImport } from './routes/_authenticated/app.journey'
import { Route as AuthenticatedAppIntelligenceRouteImport } from './routes/_authenticated/app.intelligence'
import { Route as AuthenticatedAppGrowRouteImport } from './routes/_authenticated/app.grow'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppCompetitorsRouteImport } from './routes/_authenticated/app.competitors'
import { Route as AuthenticatedAppCommunityRouteImport } from './routes/_authenticated/app.community'
import { Route as AuthenticatedAppBusinessProfileRouteImport } from './routes/_authenticated/app.business-profile'
import { Route as AuthenticatedAppBdiCompareRouteImport } from './routes/_authenticated/app.bdi-compare'
import { Route as AuthenticatedAppAlertsRouteImport } from './routes/_authenticated/app.alerts'
import { Route as AuthenticatedAppAdvisorRouteImport } from './routes/_authenticated/app.advisor'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/app.account'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerifyRoute = AuthenticatedVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicRunCiScansRoute = ApiPublicRunCiScansRouteImport.update({
  id: '/api/public/run-ci-scans',
  path: '/api/public/run-ci-scans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshCrimeBenchmarksRoute =
  ApiPublicRefreshCrimeBenchmarksRouteImport.update({
    id: '/api/public/refresh-crime-benchmarks',
    path: '/api/public/refresh-crime-benchmarks',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOpportunityFinderRoute =
  AuthenticatedAppOpportunityFinderRouteImport.update({
    id: '/opportunity-finder',
    path: '/opportunity-finder',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMarketplaceRoute =
  AuthenticatedAppMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLocationAnalysisRoute =
  AuthenticatedAppLocationAnalysisRouteImport.update({
    id: '/location-analysis',
    path: '/location-analysis',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLearningRoute =
  AuthenticatedAppLearningRouteImport.update({
    id: '/learning',
    path: '/learning',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppJourneyRoute = AuthenticatedAppJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppIntelligenceRoute =
  AuthenticatedAppIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGrowRoute = AuthenticatedAppGrowRouteImport.update({
  id: '/grow',
  path: '/grow',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCompetitorsRoute =
  AuthenticatedAppCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCommunityRoute =
  AuthenticatedAppCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBusinessProfileRoute =
  AuthenticatedAppBusinessProfileRouteImport.update({
    id: '/business-profile',
    path: '/business-profile',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBdiCompareRoute =
  AuthenticatedAppBdiCompareRouteImport.update({
    id: '/bdi-compare',
    path: '/bdi-compare',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAlertsRoute = AuthenticatedAppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdvisorRoute = AuthenticatedAppAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/discover': typeof AuthenticatedDiscoverRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/advisor': typeof AuthenticatedAppAdvisorRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/bdi-compare': typeof AuthenticatedAppBdiCompareRoute
  '/app/business-profile': typeof AuthenticatedAppBusinessProfileRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/competitors': typeof AuthenticatedAppCompetitorsRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/grow': typeof AuthenticatedAppGrowRoute
  '/app/intelligence': typeof AuthenticatedAppIntelligenceRoute
  '/app/journey': typeof AuthenticatedAppJourneyRoute
  '/app/learning': typeof AuthenticatedAppLearningRoute
  '/app/location-analysis': typeof AuthenticatedAppLocationAnalysisRoute
  '/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/app/opportunity-finder': typeof AuthenticatedAppOpportunityFinderRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/api/public/refresh-crime-benchmarks': typeof ApiPublicRefreshCrimeBenchmarksRoute
  '/api/public/run-ci-scans': typeof ApiPublicRunCiScansRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/advisor': typeof AuthenticatedAppAdvisorRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/bdi-compare': typeof AuthenticatedAppBdiCompareRoute
  '/app/business-profile': typeof AuthenticatedAppBusinessProfileRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/competitors': typeof AuthenticatedAppCompetitorsRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/grow': typeof AuthenticatedAppGrowRoute
  '/app/intelligence': typeof AuthenticatedAppIntelligenceRoute
  '/app/journey': typeof AuthenticatedAppJourneyRoute
  '/app/learning': typeof AuthenticatedAppLearningRoute
  '/app/location-analysis': typeof AuthenticatedAppLocationAnalysisRoute
  '/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/app/opportunity-finder': typeof AuthenticatedAppOpportunityFinderRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/api/public/refresh-crime-benchmarks': typeof ApiPublicRefreshCrimeBenchmarksRoute
  '/api/public/run-ci-scans': typeof ApiPublicRunCiScansRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/verify': typeof AuthenticatedVerifyRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/app/account': typeof AuthenticatedAppAccountRoute
  '/_authenticated/app/advisor': typeof AuthenticatedAppAdvisorRoute
  '/_authenticated/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/_authenticated/app/bdi-compare': typeof AuthenticatedAppBdiCompareRoute
  '/_authenticated/app/business-profile': typeof AuthenticatedAppBusinessProfileRoute
  '/_authenticated/app/community': typeof AuthenticatedAppCommunityRoute
  '/_authenticated/app/competitors': typeof AuthenticatedAppCompetitorsRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/grow': typeof AuthenticatedAppGrowRoute
  '/_authenticated/app/intelligence': typeof AuthenticatedAppIntelligenceRoute
  '/_authenticated/app/journey': typeof AuthenticatedAppJourneyRoute
  '/_authenticated/app/learning': typeof AuthenticatedAppLearningRoute
  '/_authenticated/app/location-analysis': typeof AuthenticatedAppLocationAnalysisRoute
  '/_authenticated/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/_authenticated/app/opportunity-finder': typeof AuthenticatedAppOpportunityFinderRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/api/public/refresh-crime-benchmarks': typeof ApiPublicRefreshCrimeBenchmarksRoute
  '/api/public/run-ci-scans': typeof ApiPublicRunCiScansRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app'
    | '/discover'
    | '/verify'
    | '/.mcp/invoke-tool/$tool'
    | '/app/account'
    | '/app/advisor'
    | '/app/alerts'
    | '/app/bdi-compare'
    | '/app/business-profile'
    | '/app/community'
    | '/app/competitors'
    | '/app/dashboard'
    | '/app/grow'
    | '/app/intelligence'
    | '/app/journey'
    | '/app/learning'
    | '/app/location-analysis'
    | '/app/marketplace'
    | '/app/opportunity-finder'
    | '/app/reports'
    | '/api/public/refresh-crime-benchmarks'
    | '/api/public/run-ci-scans'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/discover'
    | '/verify'
    | '/.mcp/invoke-tool/$tool'
    | '/app/account'
    | '/app/advisor'
    | '/app/alerts'
    | '/app/bdi-compare'
    | '/app/business-profile'
    | '/app/community'
    | '/app/competitors'
    | '/app/dashboard'
    | '/app/grow'
    | '/app/intelligence'
    | '/app/journey'
    | '/app/learning'
    | '/app/location-analysis'
    | '/app/marketplace'
    | '/app/opportunity-finder'
    | '/app/reports'
    | '/api/public/refresh-crime-benchmarks'
    | '/api/public/run-ci-scans'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/app'
    | '/_authenticated/discover'
    | '/_authenticated/verify'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/app/account'
    | '/_authenticated/app/advisor'
    | '/_authenticated/app/alerts'
    | '/_authenticated/app/bdi-compare'
    | '/_authenticated/app/business-profile'
    | '/_authenticated/app/community'
    | '/_authenticated/app/competitors'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/grow'
    | '/_authenticated/app/intelligence'
    | '/_authenticated/app/journey'
    | '/_authenticated/app/learning'
    | '/_authenticated/app/location-analysis'
    | '/_authenticated/app/marketplace'
    | '/_authenticated/app/opportunity-finder'
    | '/_authenticated/app/reports'
    | '/api/public/refresh-crime-benchmarks'
    | '/api/public/run-ci-scans'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicRefreshCrimeBenchmarksRoute: typeof ApiPublicRefreshCrimeBenchmarksRoute
  ApiPublicRunCiScansRoute: typeof ApiPublicRunCiScansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verify': {
      id: '/_authenticated/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthenticatedVerifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/run-ci-scans': {
      id: '/api/public/run-ci-scans'
      path: '/api/public/run-ci-scans'
      fullPath: '/api/public/run-ci-scans'
      preLoaderRoute: typeof ApiPublicRunCiScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-crime-benchmarks': {
      id: '/api/public/refresh-crime-benchmarks'
      path: '/api/public/refresh-crime-benchmarks'
      fullPath: '/api/public/refresh-crime-benchmarks'
      preLoaderRoute: typeof ApiPublicRefreshCrimeBenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/opportunity-finder': {
      id: '/_authenticated/app/opportunity-finder'
      path: '/opportunity-finder'
      fullPath: '/app/opportunity-finder'
      preLoaderRoute: typeof AuthenticatedAppOpportunityFinderRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/marketplace': {
      id: '/_authenticated/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/location-analysis': {
      id: '/_authenticated/app/location-analysis'
      path: '/location-analysis'
      fullPath: '/app/location-analysis'
      preLoaderRoute: typeof AuthenticatedAppLocationAnalysisRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/learning': {
      id: '/_authenticated/app/learning'
      path: '/learning'
      fullPath: '/app/learning'
      preLoaderRoute: typeof AuthenticatedAppLearningRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/journey': {
      id: '/_authenticated/app/journey'
      path: '/journey'
      fullPath: '/app/journey'
      preLoaderRoute: typeof AuthenticatedAppJourneyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/intelligence': {
      id: '/_authenticated/app/intelligence'
      path: '/intelligence'
      fullPath: '/app/intelligence'
      preLoaderRoute: typeof AuthenticatedAppIntelligenceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/grow': {
      id: '/_authenticated/app/grow'
      path: '/grow'
      fullPath: '/app/grow'
      preLoaderRoute: typeof AuthenticatedAppGrowRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/competitors': {
      id: '/_authenticated/app/competitors'
      path: '/competitors'
      fullPath: '/app/competitors'
      preLoaderRoute: typeof AuthenticatedAppCompetitorsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/community': {
      id: '/_authenticated/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AuthenticatedAppCommunityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/business-profile': {
      id: '/_authenticated/app/business-profile'
      path: '/business-profile'
      fullPath: '/app/business-profile'
      preLoaderRoute: typeof AuthenticatedAppBusinessProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bdi-compare': {
      id: '/_authenticated/app/bdi-compare'
      path: '/bdi-compare'
      fullPath: '/app/bdi-compare'
      preLoaderRoute: typeof AuthenticatedAppBdiCompareRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/alerts': {
      id: '/_authenticated/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AuthenticatedAppAlertsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/advisor': {
      id: '/_authenticated/app/advisor'
      path: '/advisor'
      fullPath: '/app/advisor'
      preLoaderRoute: typeof AuthenticatedAppAdvisorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/account': {
      id: '/_authenticated/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRoute
  AuthenticatedAppAdvisorRoute: typeof AuthenticatedAppAdvisorRoute
  AuthenticatedAppAlertsRoute: typeof AuthenticatedAppAlertsRoute
  AuthenticatedAppBdiCompareRoute: typeof AuthenticatedAppBdiCompareRoute
  AuthenticatedAppBusinessProfileRoute: typeof AuthenticatedAppBusinessProfileRoute
  AuthenticatedAppCommunityRoute: typeof AuthenticatedAppCommunityRoute
  AuthenticatedAppCompetitorsRoute: typeof AuthenticatedAppCompetitorsRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppGrowRoute: typeof AuthenticatedAppGrowRoute
  AuthenticatedAppIntelligenceRoute: typeof AuthenticatedAppIntelligenceRoute
  AuthenticatedAppJourneyRoute: typeof AuthenticatedAppJourneyRoute
  AuthenticatedAppLearningRoute: typeof AuthenticatedAppLearningRoute
  AuthenticatedAppLocationAnalysisRoute: typeof AuthenticatedAppLocationAnalysisRoute
  AuthenticatedAppMarketplaceRoute: typeof AuthenticatedAppMarketplaceRoute
  AuthenticatedAppOpportunityFinderRoute: typeof AuthenticatedAppOpportunityFinderRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRoute,
  AuthenticatedAppAdvisorRoute: AuthenticatedAppAdvisorRoute,
  AuthenticatedAppAlertsRoute: AuthenticatedAppAlertsRoute,
  AuthenticatedAppBdiCompareRoute: AuthenticatedAppBdiCompareRoute,
  AuthenticatedAppBusinessProfileRoute: AuthenticatedAppBusinessProfileRoute,
  AuthenticatedAppCommunityRoute: AuthenticatedAppCommunityRoute,
  AuthenticatedAppCompetitorsRoute: AuthenticatedAppCompetitorsRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppGrowRoute: AuthenticatedAppGrowRoute,
  AuthenticatedAppIntelligenceRoute: AuthenticatedAppIntelligenceRoute,
  AuthenticatedAppJourneyRoute: AuthenticatedAppJourneyRoute,
  AuthenticatedAppLearningRoute: AuthenticatedAppLearningRoute,
  AuthenticatedAppLocationAnalysisRoute: AuthenticatedAppLocationAnalysisRoute,
  AuthenticatedAppMarketplaceRoute: AuthenticatedAppMarketplaceRoute,
  AuthenticatedAppOpportunityFinderRoute:
    AuthenticatedAppOpportunityFinderRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedVerifyRoute: typeof AuthenticatedVerifyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedVerifyRoute: AuthenticatedVerifyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicRefreshCrimeBenchmarksRoute: ApiPublicRefreshCrimeBenchmarksRoute,
  ApiPublicRunCiScansRoute: ApiPublicRunCiScansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
