/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVerifyRouteImport } from './routes/_authenticated/verify'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app.reports'
import { Route as AuthenticatedAppOpportunityFinderRouteImport } from './routes/_authenticated/app.opportunity-finder'
import { Route as AuthenticatedAppMarketplaceRouteImport } from './routes/_authenticated/app.marketplace'
import { Route as AuthenticatedAppLearningRouteImport } from './routes/_authenticated/app.learning'
import { Route as AuthenticatedAppJourneyRouteImport } from './routes/_authenticated/app.journey'
import { Route as AuthenticatedAppGrowRouteImport } from './routes/_authenticated/app.grow'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppCompetitorsRouteImport } from './routes/_authenticated/app.competitors'
import { Route as AuthenticatedAppCommunityRouteImport } from './routes/_authenticated/app.community'
import { Route as AuthenticatedAppBusinessProfileRouteImport } from './routes/_authenticated/app.business-profile'
import { Route as AuthenticatedAppBdiCompareRouteImport } from './routes/_authenticated/app.bdi-compare'
import { Route as AuthenticatedAppAlertsRouteImport } from './routes/_authenticated/app.alerts'
import { Route as AuthenticatedAppAdvisorRouteImport } from './routes/_authenticated/app.advisor'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/app.account'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerifyRoute = AuthenticatedVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOpportunityFinderRoute =
  AuthenticatedAppOpportunityFinderRouteImport.update({
    id: '/opportunity-finder',
    path: '/opportunity-finder',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMarketplaceRoute =
  AuthenticatedAppMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLearningRoute =
  AuthenticatedAppLearningRouteImport.update({
    id: '/learning',
    path: '/learning',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppJourneyRoute = AuthenticatedAppJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppGrowRoute = AuthenticatedAppGrowRouteImport.update({
  id: '/grow',
  path: '/grow',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCompetitorsRoute =
  AuthenticatedAppCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCommunityRoute =
  AuthenticatedAppCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBusinessProfileRoute =
  AuthenticatedAppBusinessProfileRouteImport.update({
    id: '/business-profile',
    path: '/business-profile',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBdiCompareRoute =
  AuthenticatedAppBdiCompareRouteImport.update({
    id: '/bdi-compare',
    path: '/bdi-compare',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAlertsRoute = AuthenticatedAppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdvisorRoute = AuthenticatedAppAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/discover': typeof AuthenticatedDiscoverRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/advisor': typeof AuthenticatedAppAdvisorRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/bdi-compare': typeof AuthenticatedAppBdiCompareRoute
  '/app/business-profile': typeof AuthenticatedAppBusinessProfileRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/competitors': typeof AuthenticatedAppCompetitorsRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/grow': typeof AuthenticatedAppGrowRoute
  '/app/journey': typeof AuthenticatedAppJourneyRoute
  '/app/learning': typeof AuthenticatedAppLearningRoute
  '/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/app/opportunity-finder': typeof AuthenticatedAppOpportunityFinderRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/advisor': typeof AuthenticatedAppAdvisorRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/bdi-compare': typeof AuthenticatedAppBdiCompareRoute
  '/app/business-profile': typeof AuthenticatedAppBusinessProfileRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/competitors': typeof AuthenticatedAppCompetitorsRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/grow': typeof AuthenticatedAppGrowRoute
  '/app/journey': typeof AuthenticatedAppJourneyRoute
  '/app/learning': typeof AuthenticatedAppLearningRoute
  '/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/app/opportunity-finder': typeof AuthenticatedAppOpportunityFinderRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/verify': typeof AuthenticatedVerifyRoute
  '/_authenticated/app/account': typeof AuthenticatedAppAccountRoute
  '/_authenticated/app/advisor': typeof AuthenticatedAppAdvisorRoute
  '/_authenticated/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/_authenticated/app/bdi-compare': typeof AuthenticatedAppBdiCompareRoute
  '/_authenticated/app/business-profile': typeof AuthenticatedAppBusinessProfileRoute
  '/_authenticated/app/community': typeof AuthenticatedAppCommunityRoute
  '/_authenticated/app/competitors': typeof AuthenticatedAppCompetitorsRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/grow': typeof AuthenticatedAppGrowRoute
  '/_authenticated/app/journey': typeof AuthenticatedAppJourneyRoute
  '/_authenticated/app/learning': typeof AuthenticatedAppLearningRoute
  '/_authenticated/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/_authenticated/app/opportunity-finder': typeof AuthenticatedAppOpportunityFinderRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/pricing'
    | '/app'
    | '/discover'
    | '/verify'
    | '/app/account'
    | '/app/advisor'
    | '/app/alerts'
    | '/app/bdi-compare'
    | '/app/business-profile'
    | '/app/community'
    | '/app/competitors'
    | '/app/dashboard'
    | '/app/grow'
    | '/app/journey'
    | '/app/learning'
    | '/app/marketplace'
    | '/app/opportunity-finder'
    | '/app/reports'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/pricing'
    | '/discover'
    | '/verify'
    | '/app/account'
    | '/app/advisor'
    | '/app/alerts'
    | '/app/bdi-compare'
    | '/app/business-profile'
    | '/app/community'
    | '/app/competitors'
    | '/app/dashboard'
    | '/app/grow'
    | '/app/journey'
    | '/app/learning'
    | '/app/marketplace'
    | '/app/opportunity-finder'
    | '/app/reports'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/pricing'
    | '/_authenticated/app'
    | '/_authenticated/discover'
    | '/_authenticated/verify'
    | '/_authenticated/app/account'
    | '/_authenticated/app/advisor'
    | '/_authenticated/app/alerts'
    | '/_authenticated/app/bdi-compare'
    | '/_authenticated/app/business-profile'
    | '/_authenticated/app/community'
    | '/_authenticated/app/competitors'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/grow'
    | '/_authenticated/app/journey'
    | '/_authenticated/app/learning'
    | '/_authenticated/app/marketplace'
    | '/_authenticated/app/opportunity-finder'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verify': {
      id: '/_authenticated/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthenticatedVerifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/opportunity-finder': {
      id: '/_authenticated/app/opportunity-finder'
      path: '/opportunity-finder'
      fullPath: '/app/opportunity-finder'
      preLoaderRoute: typeof AuthenticatedAppOpportunityFinderRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/marketplace': {
      id: '/_authenticated/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/learning': {
      id: '/_authenticated/app/learning'
      path: '/learning'
      fullPath: '/app/learning'
      preLoaderRoute: typeof AuthenticatedAppLearningRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/journey': {
      id: '/_authenticated/app/journey'
      path: '/journey'
      fullPath: '/app/journey'
      preLoaderRoute: typeof AuthenticatedAppJourneyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/grow': {
      id: '/_authenticated/app/grow'
      path: '/grow'
      fullPath: '/app/grow'
      preLoaderRoute: typeof AuthenticatedAppGrowRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/competitors': {
      id: '/_authenticated/app/competitors'
      path: '/competitors'
      fullPath: '/app/competitors'
      preLoaderRoute: typeof AuthenticatedAppCompetitorsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/community': {
      id: '/_authenticated/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AuthenticatedAppCommunityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/business-profile': {
      id: '/_authenticated/app/business-profile'
      path: '/business-profile'
      fullPath: '/app/business-profile'
      preLoaderRoute: typeof AuthenticatedAppBusinessProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bdi-compare': {
      id: '/_authenticated/app/bdi-compare'
      path: '/bdi-compare'
      fullPath: '/app/bdi-compare'
      preLoaderRoute: typeof AuthenticatedAppBdiCompareRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/alerts': {
      id: '/_authenticated/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AuthenticatedAppAlertsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/advisor': {
      id: '/_authenticated/app/advisor'
      path: '/advisor'
      fullPath: '/app/advisor'
      preLoaderRoute: typeof AuthenticatedAppAdvisorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/account': {
      id: '/_authenticated/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRoute
  AuthenticatedAppAdvisorRoute: typeof AuthenticatedAppAdvisorRoute
  AuthenticatedAppAlertsRoute: typeof AuthenticatedAppAlertsRoute
  AuthenticatedAppBdiCompareRoute: typeof AuthenticatedAppBdiCompareRoute
  AuthenticatedAppBusinessProfileRoute: typeof AuthenticatedAppBusinessProfileRoute
  AuthenticatedAppCommunityRoute: typeof AuthenticatedAppCommunityRoute
  AuthenticatedAppCompetitorsRoute: typeof AuthenticatedAppCompetitorsRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppGrowRoute: typeof AuthenticatedAppGrowRoute
  AuthenticatedAppJourneyRoute: typeof AuthenticatedAppJourneyRoute
  AuthenticatedAppLearningRoute: typeof AuthenticatedAppLearningRoute
  AuthenticatedAppMarketplaceRoute: typeof AuthenticatedAppMarketplaceRoute
  AuthenticatedAppOpportunityFinderRoute: typeof AuthenticatedAppOpportunityFinderRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRoute,
  AuthenticatedAppAdvisorRoute: AuthenticatedAppAdvisorRoute,
  AuthenticatedAppAlertsRoute: AuthenticatedAppAlertsRoute,
  AuthenticatedAppBdiCompareRoute: AuthenticatedAppBdiCompareRoute,
  AuthenticatedAppBusinessProfileRoute: AuthenticatedAppBusinessProfileRoute,
  AuthenticatedAppCommunityRoute: AuthenticatedAppCommunityRoute,
  AuthenticatedAppCompetitorsRoute: AuthenticatedAppCompetitorsRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppGrowRoute: AuthenticatedAppGrowRoute,
  AuthenticatedAppJourneyRoute: AuthenticatedAppJourneyRoute,
  AuthenticatedAppLearningRoute: AuthenticatedAppLearningRoute,
  AuthenticatedAppMarketplaceRoute: AuthenticatedAppMarketplaceRoute,
  AuthenticatedAppOpportunityFinderRoute:
    AuthenticatedAppOpportunityFinderRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedVerifyRoute: typeof AuthenticatedVerifyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedVerifyRoute: AuthenticatedVerifyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
