import { Card } from "@/components/foundr/ui";
import type { Interpretation } from "@/lib/ons/types";
import { CheckCircle2, Lightbulb, ListChecks } from "lucide-react";

const SECTIONS = [
  {
    key: "fact" as const,
    label: "Fact",
    caption: "Published figures, exactly as sourced",
    icon: CheckCircle2,
    tone: "text-brand-dark",
  },
  {
    key: "inference" as const,
    label: "Inference",
    caption: "What the evidence may suggest — not proof",
    icon: Lightbulb,
    tone: "text-[color:var(--warning)]",
  },
  {
    key: "recommendation" as const,
    label: "Recommendation",
    caption: "Suggested next validation steps",
    icon: ListChecks,
    tone: "text-[color:var(--success)]",
  },
];

export function InterpretationCard({
  interpretation,
  businessType,
}: {
  interpretation: Interpretation;
  businessType: string;
}) {
  const hasContent = SECTIONS.some((s) => interpretation[s.key]?.length);
  if (!hasContent) return null;

  return (
    <Card>
      <div className="text-xs font-bold uppercase tracking-wider text-brand-dark">
        What this means for a {businessType.toLowerCase()}
      </div>
      <div className="mt-4 space-y-4">
        {SECTIONS.map((s) => {
          const items = interpretation[s.key];
          if (!items?.length) return null;
          const Icon = s.icon;
          return (
            <div key={s.key}>
              <div className={`flex items-center gap-2 text-xs font-bold uppercase tracking-wider ${s.tone}`}>
                <Icon className="h-3.5 w-3.5" /> {s.label}
                <span className="font-normal normal-case tracking-normal text-muted-foreground">— {s.caption}</span>
              </div>
              <ul className="mt-2 space-y-1.5 text-sm">
                {items.map((item) => (
                  <li key={item} className="text-muted-foreground">
                    • {item}
                  </li>
                ))}
              </ul>
            </div>
          );
        })}
      </div>
      <p className="mt-4 text-[11px] text-muted-foreground">
        Interpretation is generated by Found-r's AI from the ONS figures listed under Evidence used. It does not add new
        statistics, and demographic evidence alone cannot establish commercial viability.
      </p>
    </Card>
  );
}
